---
title: "Dataset"
output:
  html_document:
    df_print: paged
---

```{r}
d1.x.df <- read.csv("C:/datamining/dataset/Abia_Rural_x.csv")
d2.x.df <- read.csv("C:/datamining/dataset/Abia_Urban_x.csv")
d3.x.df <- read.csv("C:/datamining/dataset/Adamawa_Rural_x.csv")
d4.x.df <- read.csv("C:/datamining/dataset/Adamawa_Urban_x.csv")
d5.x.df <- read.csv("C:/datamining/dataset/Akwa_Ibom_Rural_x.csv")
d6.x.df <- read.csv("C:/datamining/dataset/Akwa_Ibom_Urban_x.csv")
d7.x.df <- read.csv("C:/datamining/dataset/Anambra_Rural_x.csv")
d8.x.df <- read.csv("C:/datamining/dataset/Anambra_Urban_x.csv")
d9.x.df <- read.csv("C:/datamining/dataset/Bauchi_Rural_x.csv")
d10.x.df <- read.csv("C:/datamining/dataset/Bauchi_Urban_x.csv")
d11.x.df <- read.csv("C:/datamining/dataset/Bayelsa_Rural_x.csv")
d12.x.df <- read.csv("C:/datamining/dataset/Bayelsa_Urban_x.csv")
d13.x.df <- read.csv("C:/datamining/dataset/Benue_Rural_x.csv")
d14.x.df <- read.csv("C:/datamining/dataset/Benue_Urban_x.csv")
d15.x.df <- read.csv("C:/datamining/dataset/Borno_Rural_x.csv")
d16.x.df <- read.csv("C:/datamining/dataset/Borno_Urban_x.csv")
d17.x.df <- read.csv("C:/datamining/dataset/Cross_River_Rural_x.csv")
d18.x.df <- read.csv("C:/datamining/dataset/Cross_River_Urban_x.csv")
d19.x.df <- read.csv("C:/datamining/dataset/Delta_Rural_x.csv")
d20.x.df <- read.csv("C:/datamining/dataset/Delta_Urban_x.csv")
d21.x.df <- read.csv("C:/datamining/dataset/Ebonyi_Rural_x.csv")
d22.x.df <- read.csv("C:/datamining/dataset/Ebonyi_Urban_x.csv")
d23.x.df <- read.csv("C:/datamining/dataset/Edo_Rural_x.csv")
d24.x.df <- read.csv("C:/datamining/dataset/Edo_Urban_x.csv")
d25.x.df <- read.csv("C:/datamining/dataset/Ekiti_Rural_x.csv")
d26.x.df <- read.csv("C:/datamining/dataset/Ekiti_Urban_x.csv")
d27.x.df <- read.csv("C:/datamining/dataset/Enugu_Rural_x.csv")
d28.x.df <- read.csv("C:/datamining/dataset/Enugu_Urban_x.csv")
d29.x.df <- read.csv("C:/datamining/dataset/Federal_Capital_Territory_Rural_x.csv")
d30.x.df <- read.csv("C:/datamining/dataset/Federal_Capital_Territory_Urban_x.csv")
d31.x.df <- read.csv("C:/datamining/dataset/Gombe_Rural_x.csv")
d32.x.df <- read.csv("C:/datamining/dataset/Gombe_Urban_x.csv")
d33.x.df <- read.csv("C:/datamining/dataset/Imo_Rural_x.csv")
d34.x.df <- read.csv("C:/datamining/dataset/Imo_Urban_x.csv")
d35.x.df <- read.csv("C:/datamining/dataset/Jigawa_Rural_x.csv")
d36.x.df <- read.csv("C:/datamining/dataset/Jigawa_Urban_x.csv")
d37.x.df <- read.csv("C:/datamining/dataset/Kaduna_Rural_x.csv")
d38.x.df <- read.csv("C:/datamining/dataset/Kaduna_Urban_x.csv")
d39.x.df <- read.csv("C:/datamining/dataset/Kano_Rural_x.csv")
d40.x.df <- read.csv("C:/datamining/dataset/Kano_Urban_x.csv")
d41.x.df <- read.csv("C:/datamining/dataset/Katsina_Rural_x.csv")
d42.x.df <- read.csv("C:/datamining/dataset/Katsina_Urban_x.csv")
d43.x.df <- read.csv("C:/datamining/dataset/Kebbi_Rural_x.csv")
d44.x.df <- read.csv("C:/datamining/dataset/Kebbi_Urban_x.csv")
d45.x.df <- read.csv("C:/datamining/dataset/Kogi_Rural_x.csv")
d46.x.df <- read.csv("C:/datamining/dataset/Kogi_Urban_x.csv")
d47.x.df <- read.csv("C:/datamining/dataset/Kwara_Rural_x.csv")
d48.x.df <- read.csv("C:/datamining/dataset/Kwara_Urban_x.csv")
d49.x.df <- read.csv("C:/datamining/dataset/Lagos_Rural_x.csv")
d50.x.df <- read.csv("C:/datamining/dataset/Lagos_Urban_x.csv")
d51.x.df <- read.csv("C:/datamining/dataset/Nasarawa_Rural_x.csv")
d52.x.df <- read.csv("C:/datamining/dataset/Nasarawa_Urban_x.csv")
d53.x.df <- read.csv("C:/datamining/dataset/Niger_Rural_x.csv")
d54.x.df <- read.csv("C:/datamining/dataset/Niger_Urban_x.csv")
d55.x.df <- read.csv("C:/datamining/dataset/Ogun_Rural_x.csv")
d56.x.df <- read.csv("C:/datamining/dataset/Ogun_Urban_x.csv")
d57.x.df <- read.csv("C:/datamining/dataset/Ondo_Rural_x.csv")
d58.x.df <- read.csv("C:/datamining/dataset/Ondo_Urban_x.csv")
d59.x.df <- read.csv("C:/datamining/dataset/Osun_Rural_x.csv")
d60.x.df <- read.csv("C:/datamining/dataset/Osun_Urban_x.csv")
d61.x.df <- read.csv("C:/datamining/dataset/Oyo_Rural_x.csv")
d62.x.df <- read.csv("C:/datamining/dataset/Oyo_Urban_x.csv")
d63.x.df <- read.csv("C:/datamining/dataset/Plateau_Rural_x.csv")
d64.x.df <- read.csv("C:/datamining/dataset/Plateau_Urban_x.csv")
d65.x.df <- read.csv("C:/datamining/dataset/Rivers_Rural_x.csv")
d66.x.df <- read.csv("C:/datamining/dataset/Rivers_Urban_x.csv")
d67.x.df <- read.csv("C:/datamining/dataset/Sokoto_Rural_x.csv")
d68.x.df <- read.csv("C:/datamining/dataset/Sokoto_Urban_x.csv")
d69.x.df <- read.csv("C:/datamining/dataset/Taraba_Rural_x.csv")
d70.x.df <- read.csv("C:/datamining/dataset/Taraba_Urban_x.csv")
d71.x.df <- read.csv("C:/datamining/dataset/Yobe_Rural_x.csv")
d72.x.df <- read.csv("C:/datamining/dataset/Yobe_Urban_x.csv")
d73.x.df <- read.csv("C:/datamining/dataset/Zamfara_Rural_x.csv")
d74.x.df <- read.csv("C:/datamining/dataset/Zamfara_Urban_x.csv")
```

```{r}
d1.y.df <- read.csv("C:/datamining/dataset/Abia_Rural_y.csv")
d2.y.df <- read.csv("C:/datamining/dataset/Abia_Urban_y.csv")
d3.y.df <- read.csv("C:/datamining/dataset/Adamawa_Rural_y.csv")
d4.y.df <- read.csv("C:/datamining/dataset/Adamawa_Urban_y.csv")
d5.y.df <- read.csv("C:/datamining/dataset/Akwa_Ibom_Rural_y.csv")
d6.y.df <- read.csv("C:/datamining/dataset/Akwa_Ibom_Urban_y.csv")
d7.y.df <- read.csv("C:/datamining/dataset/Anambra_Rural_y.csv")
d8.y.df <- read.csv("C:/datamining/dataset/Anambra_Urban_y.csv")
d9.y.df <- read.csv("C:/datamining/dataset/Bauchi_Rural_y.csv")
d10.y.df <- read.csv("C:/datamining/dataset/Bauchi_Urban_y.csv")
d11.y.df <- read.csv("C:/datamining/dataset/Bayelsa_Rural_y.csv")
d12.y.df <- read.csv("C:/datamining/dataset/Bayelsa_Urban_y.csv")
d13.y.df <- read.csv("C:/datamining/dataset/Benue_Rural_y.csv")
d14.y.df <- read.csv("C:/datamining/dataset/Benue_Urban_y.csv")
d15.y.df <- read.csv("C:/datamining/dataset/Borno_Rural_y.csv")
d16.y.df <- read.csv("C:/datamining/dataset/Borno_Urban_y.csv")
d17.y.df <- read.csv("C:/datamining/dataset/Cross_River_Rural_y.csv")
d18.y.df <- read.csv("C:/datamining/dataset/Cross_River_Urban_y.csv")
d19.y.df <- read.csv("C:/datamining/dataset/Delta_Rural_y.csv")
d20.y.df <- read.csv("C:/datamining/dataset/Delta_Urban_y.csv")
d21.y.df <- read.csv("C:/datamining/dataset/Ebonyi_Rural_y.csv")
d22.y.df <- read.csv("C:/datamining/dataset/Ebonyi_Urban_y.csv")
d23.y.df <- read.csv("C:/datamining/dataset/Edo_Rural_y.csv")
d24.y.df <- read.csv("C:/datamining/dataset/Edo_Urban_y.csv")
d25.y.df <- read.csv("C:/datamining/dataset/Ekiti_Rural_y.csv")
d26.y.df <- read.csv("C:/datamining/dataset/Ekiti_Urban_y.csv")
d27.y.df <- read.csv("C:/datamining/dataset/Enugu_Rural_y.csv")
d28.y.df <- read.csv("C:/datamining/dataset/Enugu_Urban_y.csv")
d29.y.df <- read.csv("C:/datamining/dataset/Federal_Capital_Territory_Rural_y.csv")
d30.y.df <- read.csv("C:/datamining/dataset/Federal_Capital_Territory_Urban_y.csv")
d31.y.df <- read.csv("C:/datamining/dataset/Gombe_Rural_y.csv")
d32.y.df <- read.csv("C:/datamining/dataset/Gombe_Urban_y.csv")
d33.y.df <- read.csv("C:/datamining/dataset/Imo_Rural_y.csv")
d34.y.df <- read.csv("C:/datamining/dataset/Imo_Urban_y.csv")
d35.y.df <- read.csv("C:/datamining/dataset/Jigawa_Rural_y.csv")
d36.y.df <- read.csv("C:/datamining/dataset/Jigawa_Urban_y.csv")
d37.y.df <- read.csv("C:/datamining/dataset/Kaduna_Rural_y.csv")
d38.y.df <- read.csv("C:/datamining/dataset/Kaduna_Urban_y.csv")
d39.y.df <- read.csv("C:/datamining/dataset/Kano_Rural_y.csv")
d40.y.df <- read.csv("C:/datamining/dataset/Kano_Urban_y.csv")
d41.y.df <- read.csv("C:/datamining/dataset/Katsina_Rural_y.csv")
d42.y.df <- read.csv("C:/datamining/dataset/Katsina_Urban_y.csv")
d43.y.df <- read.csv("C:/datamining/dataset/Kebbi_Rural_y.csv")
d44.y.df <- read.csv("C:/datamining/dataset/Kebbi_Urban_y.csv")
d45.y.df <- read.csv("C:/datamining/dataset/Kogi_Rural_y.csv")
d46.y.df <- read.csv("C:/datamining/dataset/Kogi_Urban_y.csv")
d47.y.df <- read.csv("C:/datamining/dataset/Kwara_Rural_y.csv")
d48.y.df <- read.csv("C:/datamining/dataset/Kwara_Urban_y.csv")
d49.y.df <- read.csv("C:/datamining/dataset/Lagos_Rural_y.csv")
d50.y.df <- read.csv("C:/datamining/dataset/Lagos_Urban_y.csv")
d51.y.df <- read.csv("C:/datamining/dataset/Nasarawa_Rural_y.csv")
d52.y.df <- read.csv("C:/datamining/dataset/Nasarawa_Urban_y.csv")
d53.y.df <- read.csv("C:/datamining/dataset/Niger_Rural_y.csv")
d54.y.df <- read.csv("C:/datamining/dataset/Niger_Urban_y.csv")
d55.y.df <- read.csv("C:/datamining/dataset/Ogun_Rural_y.csv")
d56.y.df <- read.csv("C:/datamining/dataset/Ogun_Urban_y.csv")
d57.y.df <- read.csv("C:/datamining/dataset/Ondo_Rural_y.csv")
d58.y.df <- read.csv("C:/datamining/dataset/Ondo_Urban_y.csv")
d59.y.df <- read.csv("C:/datamining/dataset/Osun_Rural_y.csv")
d60.y.df <- read.csv("C:/datamining/dataset/Osun_Urban_y.csv")
d61.y.df <- read.csv("C:/datamining/dataset/Oyo_Rural_y.csv")
d62.y.df <- read.csv("C:/datamining/dataset/Oyo_Urban_y.csv")
d63.y.df <- read.csv("C:/datamining/dataset/Plateau_Rural_y.csv")
d64.y.df <- read.csv("C:/datamining/dataset/Plateau_Urban_y.csv")
d65.y.df <- read.csv("C:/datamining/dataset/Rivers_Rural_y.csv")
d66.y.df <- read.csv("C:/datamining/dataset/Rivers_Urban_y.csv")
d67.y.df <- read.csv("C:/datamining/dataset/Sokoto_Rural_y.csv")
d68.y.df <- read.csv("C:/datamining/dataset/Sokoto_Urban_y.csv")
d69.y.df <- read.csv("C:/datamining/dataset/Taraba_Rural_y.csv")
d70.y.df <- read.csv("C:/datamining/dataset/Taraba_Urban_y.csv")
d71.y.df <- read.csv("C:/datamining/dataset/Yobe_Rural_y.csv")
d72.y.df <- read.csv("C:/datamining/dataset/Yobe_Urban_y.csv")
d73.y.df <- read.csv("C:/datamining/dataset/Zamfara_Rural_y.csv")
d74.y.df <- read.csv("C:/datamining/dataset/Zamfara_Urban_y.csv")
```

```{r}
Y = d74.y.df[,2]
d74 = cbind(d74.x.df[,2:4], Y)
```


#make traindata
```{r}
train = rbind(d1[1:34,], d2[1:34,])
train = rbind(train, d3[1:34,])
train = rbind(train, d4[1:34,])
train = rbind(train, d5[1:34,])
train = rbind(train, d6[1:34,])
train = rbind(train, d7[1:34,])
train = rbind(train, d8[1:34,])
train = rbind(train, d9[1:34,])
train = rbind(train, d10[1:34,])
train = rbind(train, d11[1:34,])
train = rbind(train, d12[1:34,])
train = rbind(train, d13[1:34,])
train = rbind(train, d14[1:34,])
train = rbind(train, d15[1:34,])
train = rbind(train, d16[1:34,])
train = rbind(train, d17[1:34,])
train = rbind(train, d18[1:34,])
train = rbind(train, d19[1:34,])
train = rbind(train, d20[1:34,])
train = rbind(train, d21[1:34,])
train = rbind(train, d22[1:34,])
train = rbind(train, d23[1:34,])
train = rbind(train, d24[1:34,])
train = rbind(train, d25[1:34,])
train = rbind(train, d26[1:34,])
train = rbind(train, d27[1:34,])
train = rbind(train, d28[1:34,])
train = rbind(train, d29[1:34,])
train = rbind(train, d30[1:34,])
train = rbind(train, d31[1:34,])
train = rbind(train, d32[1:34,])
train = rbind(train, d33[1:34,])
train = rbind(train, d34[1:34,])
train = rbind(train, d35[1:34,])
train = rbind(train, d36[1:34,])
train = rbind(train, d37[1:34,])
train = rbind(train, d38[1:34,])
train = rbind(train, d39[1:34,])
train = rbind(train, d40[1:34,])
train = rbind(train, d41[1:34,])
train = rbind(train, d42[1:34,])
train = rbind(train, d43[1:34,])
train = rbind(train, d44[1:34,])
train = rbind(train, d45[1:34,])
train = rbind(train, d46[1:34,])
train = rbind(train, d47[1:34,])
train = rbind(train, d48[1:34,])
train = rbind(train, d49[1:34,])
train = rbind(train, d50[1:34,])
train = rbind(train, d51[1:34,])
train = rbind(train, d52[1:34,])
train = rbind(train, d53[1:34,])
train = rbind(train, d54[1:34,])
train = rbind(train, d55[1:34,])
train = rbind(train, d56[1:34,])
train = rbind(train, d57[1:34,])
train = rbind(train, d58[1:34,])
train = rbind(train, d59[1:34,])
train = rbind(train, d60[1:34,])
train = rbind(train, d61[1:34,])
train = rbind(train, d62[1:34,])
train = rbind(train, d63[1:34,])
train = rbind(train, d64[1:34,])
train = rbind(train, d65[1:34,])
train = rbind(train, d66[1:34,])
train = rbind(train, d67[1:34,])
train = rbind(train, d68[1:34,])
train = rbind(train, d69[1:34,])
train = rbind(train, d70[1:34,])
train = rbind(train, d71[1:34,])
train = rbind(train, d72[1:34,])
train = rbind(train, d73[1:34,])
train = rbind(train, d74[1:34,])
```

```{r}
train.normal = train[(train$X1 < 6 & train$X2 < 6 & train$X3 < 6 & train$Y < 6), ]
```


#make validationset
```{r}
val = rbind(d1[36:47,], d2[36:47,])
val = rbind(val, d3[36:47,])
val = rbind(val, d4[36:47,])
val = rbind(val, d5[36:47,])
val = rbind(val, d6[36:47,])
val = rbind(val, d7[36:47,])
val = rbind(val, d8[36:47,])
val = rbind(val, d9[36:47,])
val = rbind(val, d10[36:47,])
val = rbind(val, d11[36:47,])
val = rbind(val, d12[36:47,])
val = rbind(val, d13[36:47,])
val = rbind(val, d14[36:47,])
val = rbind(val, d15[36:47,])
val = rbind(val, d16[36:47,])
val = rbind(val, d17[36:47,])
val = rbind(val, d18[36:47,])
val = rbind(val, d19[36:47,])
val = rbind(val, d20[36:47,])
val = rbind(val, d21[36:47,])
val = rbind(val, d22[36:47,])
val = rbind(val, d23[36:47,])
val = rbind(val, d24[36:47,])
val = rbind(val, d25[36:47,])
val = rbind(val, d26[36:47,])
val = rbind(val, d27[36:47,])
val = rbind(val, d28[36:47,])
val = rbind(val, d29[36:47,])
val = rbind(val, d30[36:47,])
val = rbind(val, d31[36:47,])
val = rbind(val, d32[36:47,])
val = rbind(val, d33[36:47,])
val = rbind(val, d34[36:47,])
val = rbind(val, d35[36:47,])
val = rbind(val, d36[36:47,])
val = rbind(val, d37[36:47,])
val = rbind(val, d38[36:47,])
val = rbind(val, d39[36:47,])
val = rbind(val, d40[36:47,])
val = rbind(val, d41[36:47,])
val = rbind(val, d42[36:47,])
val = rbind(val, d43[36:47,])
val = rbind(val, d44[36:47,])
val = rbind(val, d45[36:47,])
val = rbind(val, d46[36:47,])
val = rbind(val, d47[36:47,])
val = rbind(val, d48[36:47,])
val = rbind(val, d49[36:47,])
val = rbind(val, d50[36:47,])
val = rbind(val, d51[36:47,])
val = rbind(val, d52[36:47,])
val = rbind(val, d53[36:47,])
val = rbind(val, d54[36:47,])
val = rbind(val, d55[36:47,])
val = rbind(val, d56[36:47,])
val = rbind(val, d57[36:47,])
val = rbind(val, d58[36:47,])
val = rbind(val, d59[36:47,])
val = rbind(val, d60[36:47,])
val = rbind(val, d61[36:47,])
val = rbind(val, d62[36:47,])
val = rbind(val, d63[36:47,])
val = rbind(val, d64[36:47,])
val = rbind(val, d65[36:47,])
val = rbind(val, d66[36:47,])
val = rbind(val, d67[36:47,])
val = rbind(val, d68[36:47,])
val = rbind(val, d69[36:47,])
val = rbind(val, d70[36:47,])
val = rbind(val, d71[36:47,])
val = rbind(val, d72[36:47,])
val = rbind(val, d73[36:47,])
val = rbind(val, d74[36:47,])
```

#val(spread ver)
```{r}
val.spread = val[(val$Y >5),]
```

#val(normal ver)
```{r}
val.normal = val[(val$X1 < 6 & val$X2 < 6 & val$X3 < 6 & val$Y < 6), ]
```

```{r}
n = dim(val.normal)[1]/2
val.normal1 = val.normal[1:n,]
val.normal2 = val.normal[(n+1):dim(val.normal)[1],]
```

#make testset
```{r}
test = rbind(d1[49:59,], d2[49:59,])
test = rbind(test, d3[49:59,])
test = rbind(test, d4[49:59,])
test = rbind(test, d5[49:59,])
test = rbind(test, d6[49:59,])
test = rbind(test, d7[49:59,])
test = rbind(test, d8[49:59,])
test = rbind(test, d9[49:59,])
test = rbind(test, d10[49:59,])
test = rbind(test, d11[49:59,])
test = rbind(test, d12[49:59,])
test = rbind(test, d13[49:59,])
test = rbind(test, d14[49:59,])
test = rbind(test, d15[49:59,])
test = rbind(test, d16[49:59,])
test = rbind(test, d17[49:59,])
test = rbind(test, d18[49:59,])
test = rbind(test, d19[49:59,])
test = rbind(test, d20[49:59,])
test = rbind(test, d21[49:59,])
test = rbind(test, d22[49:59,])
test = rbind(test, d23[49:59,])
test = rbind(test, d24[49:59,])
test = rbind(test, d25[49:59,])
test = rbind(test, d26[49:59,])
test = rbind(test, d27[49:59,])
test = rbind(test, d28[49:59,])
test = rbind(test, d29[49:59,])
test = rbind(test, d30[49:59,])
test = rbind(test, d31[49:59,])
test = rbind(test, d32[49:59,])
test = rbind(test, d33[49:59,])
test = rbind(test, d34[49:59,])
test = rbind(test, d35[49:59,])
test = rbind(test, d36[49:59,])
test = rbind(test, d37[49:59,])
test = rbind(test, d38[49:59,])
test = rbind(test, d39[49:59,])
test = rbind(test, d40[49:59,])
test = rbind(test, d41[49:59,])
test = rbind(test, d42[49:59,])
test = rbind(test, d43[49:59,])
test = rbind(test, d44[49:59,])
test = rbind(test, d45[49:59,])
test = rbind(test, d46[49:59,])
test = rbind(test, d47[49:59,])
test = rbind(test, d48[49:59,])
test = rbind(test, d49[49:59,])
test = rbind(test, d50[49:59,])
test = rbind(test, d51[49:59,])
test = rbind(test, d52[49:59,])
test = rbind(test, d53[49:59,])
test = rbind(test, d54[49:59,])
test = rbind(test, d55[49:59,])
test = rbind(test, d56[49:59,])
test = rbind(test, d57[49:59,])
test = rbind(test, d58[49:59,])
test = rbind(test, d59[49:59,])
test = rbind(test, d60[49:59,])
test = rbind(test, d61[49:59,])
test = rbind(test, d62[49:59,])
test = rbind(test, d63[49:59,])
test = rbind(test, d64[49:59,])
test = rbind(test, d65[49:59,])
test = rbind(test, d66[49:59,])
test = rbind(test, d67[49:59,])
test = rbind(test, d68[49:59,])
test = rbind(test, d69[49:59,])
test = rbind(test, d70[49:59,])
test = rbind(test, d71[49:59,])
test = rbind(test, d72[49:59,])
test = rbind(test, d73[49:59,])
test = rbind(test, d74[49:59,])
```

#test (spread ver)
```{r}
test.spread = test[(test$Y >5),]
```

#test (normal ver)
```{r}
test.normal = test[(test$X1 < 6 & test$X2 < 6 & test$X3 < 6 & test$Y < 6), ]
```


#저장
```{r}
write.csv(train.normal, "train_normal.csv")
write.csv(val.spread, "val_spread.csv")
write.csv(val.normal1, "val_normal1.csv")
write.csv(val.normal2, "val_normal2.csv")
write.csv(test.spread, "test_spread.csv")
write.csv(test.normal, "test_normal.csv")
```

